### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by KogutGaming** [Makenekoooo/DredayStyleChnager#1]
how to use this?

**Comment by Makenekoooo** [comment]
do you mean the extension is not be enabled?
If you already had the Dredark page open when you installed the extension, you need to reopen the Dredark page to enabled

**Comment by KogutGaming** [comment]
*how to install it
*

**Comment by Makenekoooo** [comment]
oh didn't you came here from store page?
here is store page
https://chrome.google.com/webstore/detail/dredark-style-changer/ihnjdomcfjgekabadgkoopildcmbgimp?hl=en&authuser=0

**Comment by KogutGaming** [comment]
thx
